name: A workflow for my Hello World file
on:
  push:
    tags: test/*

env:
  GITHUB_REGISTRY: ghrc.io
  MY_NAME: john
  REF_NAME: ${{ github.ref_name }}

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: echo my_name is ${MY_NAME}, ref_name is ${REF_NAME};
      - run: echo prefix ${REF_NAME#*/}, suffix is ${REF_NAME%/*};
      # - uses: actions/checkout@v4
      # - uses: ./action-a
      #   with:
      #     MY_NAME: "Mona"
