name: A workflow for my Hello World file
on:
  issues:
    # types: [opened, edited]
    types: [edited]
env:
  GITHUB_REGISTRY: ghrc.io
  MY_NAME: john
  REF_NAME: ${{ github.ref_name }}

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'build')
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: echo my_name is ${MY_NAME}, ref_name is ${REF_NAME} .
      - run: echo prefix ${REF_NAME%/*}, suffix is ${REF_NAME#*/} .

      - uses: actions/checkout/@v4
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: latest-tag
      - run: echo latest tag ${{ steps.latest-tag.outputs.tag }}

      # Env vars
      - run: echo "SANITY=yes" >> "$GITHUB_ENV"
      - run: echo sane? ${SANITY} .
      - run: echo "NN_TAG=${{ steps.latest-tag.outputs.tag }}" >> "$GITHUB_ENV"
      - run: echo NN_TAG is ${NN_TAG} .
      - run: echo prefix ${NN_TAG%/*}, suffix is ${NN_TAG#*/} .
      # - run: echo ${{ github.event.issue.comments }}

      - run: echo found label "build"
        if: contains(github.event.issue.labels.*.name, 'build')
