name: A workflow for my Hello World file
on:
  issues:
    types: [opened, edited]
  # push:
  #   tags: test/*

env:
  GITHUB_REGISTRY: ghrc.io
  MY_NAME: john
  REF_NAME: ${{ github.ref_name }}
  # LABELS: ${{ github.event.issue.labels }}

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: echo my_name is ${MY_NAME}, ref_name is ${REF_NAME};
      - run: echo prefix ${REF_NAME%/*}, suffix is ${REF_NAME#*/};

      - uses: actions/checkout/@v4
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - run: echo latest tag ${{ steps.get-latest-tag.outputs.tag }}

      # - run: echo labels "${LABELS[*]}";
      - run: echo found lable "build"
        if: contains(github.event.issue.labels.*.name, 'build')


      # - run: echo explicit tag name is ${EXPLICIT_TAG_NAME}
      # - uses: actions/checkout@v4
      # - uses: ./action-a
      #   with:
      #     MY_NAME: "Mona"
