name: Test workflow actions
on:
  workflow_dispatch
  # issues:
    # types: [opened, edited]
    # types: [edited]
env:
  GITHUB_REGISTRY: ghrc.io
  MY_NAME: john
  REF_NAME: ${{ github.ref_name }}
  IMAGE_NAME: test

jobs:
  get-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-repo-tag.outputs.tag }}
      test_string: xyzzy
    steps:
      - uses: actions/checkout/@v4
        with:
          fetch-depth: 0
      - run: echo IMAGE_NAME is ${IMAGE_NAME}
      - run: echo env.IMAGE_NAME double is ${{ env.IMAGE_NAME }}

      - run: echo $(git describe --tags --match="test/*" --abbrev=0)
      - run: echo $(git describe --tags --match="${IMAGE_NAME}/*" --abbrev=0)
      - id: get-repo-tag
        # No command substitution because I just cannot figure it out
        run: echo tag=$(git describe --tags --match="test/*" --abbrev=0) >> "$GITHUB_OUTPUT"

  build:
    # if: contains(github.event.issue.labels.*.name, 'build')
    name: Hello world action
    runs-on: ubuntu-latest
    needs: get-image-tag
    steps:
      - run: echo my_name is ${MY_NAME}, ref_name is ${REF_NAME} .
      - run: echo prefix ${REF_NAME%/*}, suffix is ${REF_NAME#*/} .

      - run: echo test_string is ${{ needs.get-image-tag.outputs.test_string }}
      - run: echo input string is ${{ needs.get-image-tag.outputs.image_tag }}
      - run: echo "IMAGE_TAG=${{ needs.get-image-tag.outputs.image_tag }}" >> $GITHUB_ENV
      - run: echo "IMAGE_TAG is ${IMAGE_TAG}"

      # - uses: actions/checkout/@v4
      # - uses: actions-ecosystem/action-get-latest-tag@v1
      #   id: latest-tag
      # - run: echo latest tag ${{ steps.latest-tag.outputs.tag }}

      # Env vars
      # - run: echo "SANITY=yes" >> "$GITHUB_ENV"
      # - run: echo sane? ${SANITY} .
      # - run: echo "NN_TAG=${{ steps.latest-tag.outputs.tag }}" >> "$GITHUB_ENV"
      # - run: echo NN_TAG is ${NN_TAG} .
      # - run: echo prefix ${NN_TAG%/*}, suffix is ${NN_TAG#*/} .
      # - run: echo ${{ github.event.issue.comments }}
